### ISSUE TITLE
Page Headers

### ISSUE THREAD

**Issue by MiguelJeme** [yescomment/jm-srf#1]
- [x] Left Margin: Align with blue section text 
- [x] Right Margin: Make a space/ gap with photo 
- [x] Intro blurb: font size twice as big, Use Ebony LT
<img width="1080" alt="Screenshot 2024-02-29 at 10 24 37 AM" src="https://github.com/yescomment/jm-srf/assets/161371893/a16fdb98-2957-4326-87ec-95d05b98a0b1">

**Comment by MiguelJeme** [comment]
Photo and color block Overlap:
1. Make all the overlaps more consistent across pages.
2. Make them overlap more
<img width="854" alt="Screenshot 2024-02-29 at 10 34 32 AM" src="https://github.com/yescomment/jm-srf/assets/161371893/4b23ed40-8705-4240-b11f-307d8b0332f0">

**Comment by unitof** [comment]
Twice as big was HUGE.
<img width="1620" alt="20643" src="https://github.com/yescomment/jm-srf/assets/2448782/0fdbc0d7-4a72-4300-934a-a4e262a65afe">

Going with 1.5rem (1.5× default body size). Seems closer to your mockup.

Images will now always crop to 3:4 vertical so I can predict position.
