### ISSUE TITLE
Footer design for both sites

### ISSUE THREAD

**Issue by MiguelJeme** [yescomment/jm-srf#11]
<img width="910" alt="Screenshot 2024-04-12 at 2 18 15 PM" src="https://github.com/yescomment/jm-srf/assets/161371893/34415a2d-d920-41a9-9f93-80f59c587cf5">
<img width="1013" alt="Screenshot 2024-04-12 at 2 18 29 PM" src="https://github.com/yescomment/jm-srf/assets/161371893/0c52dafc-60d1-4124-9ffd-f4c232dc59c2">

**Comment by unitof** [comment]
Weird glitch where icon refused to load on impact—will figure out later
