### ISSUE TITLE
General Headers + layout

### ISSUE THREAD

**Issue by MiguelJeme** [yescomment/jm-srf#13]
This PDF includes 
 [SRF Web Layout Updates.pdf](https://github.com/yescomment/jm-srf/files/14962208/SRF.Web.Layout.Updates.pdf)

- the updates to photo strip removal
- added spacing between paragraphs/sections, 
- margins adjustments
- Plant proportions

Included a few examples of how the plants size contraints.
<img width="624" alt="Screenshot 2024-04-12 at 2 22 12 PM" src="https://github.com/yescomment/jm-srf/assets/161371893/3bfe25c3-aae0-4eea-8e15-5ec285ff4b1d">
<img width="759" alt="Screenshot 2024-04-12 at 2 22 50 PM" src="https://github.com/yescomment/jm-srf/assets/161371893/aa20e2b3-958e-478e-ab47-72b53bae61a0">
<img width="759" alt="Screenshot 2024-04-12 at 2 23 31 PM" src="https://github.com/yescomment/jm-srf/assets/161371893/15600e12-4ba3-4253-96c5-0e03e1a862c2">

**Comment by unitof** [comment]
Think we got all this. Closing, but reopen if anything missing @MiguelJeme.
