### ISSUE TITLE
Dorian doesn't like the colrs boxes around h3s, or in the header & footer. Doesn't seem to like boxes around anything.

### ISSUE THREAD

**Issue by unitof** [yescomment/jm-srf#20]

**Comment by unitof** [comment]
@MiguelJeme went with plain text. Tried underline (see below) but feel like Dorian won't love that either.

Plain text feels nice and airy.
<img width="1618" alt="image" src="https://github.com/yescomment/jm-srf/assets/2448782/4afeffb5-318a-45ca-8810-cefe15ef6468">

**Comment by MiguelJeme** [comment]
@unitof yeah agreed. or a thinner stroke

Could H3 sections be indented to add visual break and hierarchy?
