### ISSUE TITLE
Body Content Format

### ISSUE THREAD

**Issue by MiguelJeme** [yescomment/jm-srf#3]
**H3:** change to Ivy Mode Regular
- Increase section / paragraph spacing above H3 by 60%

**Body / standard copy:**
- Ebony LT
- Decrease size by 1 or 2

**H4:** Stretch blue box to the left (if possible)
- Can the blue box fade-slide/animate in?

<img width="1188" alt="Screenshot 2024-02-29 at 1 40 48 PM" src="https://github.com/yescomment/jm-srf/assets/161371893/35e76ea4-8087-4639-9d7c-65a7dca1762b">

**Comment by unitof** [comment]
Now like a leaf flapping in the wind

https://github.com/yescomment/jm-srf/assets/2448782/698c09b1-6eeb-41f8-99d5-b28014bf1fcb
