### ISSUE TITLE
Capital: (W)Health+ page 

### ISSUE THREAD

**Issue by MiguelJeme** [yescomment/jm-srf#5]
Static Option:
Re-layout bullet list into quadrants
<img width="782" alt="Screenshot 2024-03-06 at 1 51 42 PM" src="https://github.com/yescomment/jm-srf/assets/161371893/a3a7a816-ee1a-4ccc-9bd2-26bef8aea779">

**Comment by MiguelJeme** [comment]
Motion/Interactive Option:
Mimic this cycle-through [link](https://www.pinterest.com/pin/346284658865455648/)

The large word and the blurb would change while the rest remains static
<img width="861" alt="Screenshot 2024-03-06 at 2 20 48 PM" src="https://github.com/yescomment/jm-srf/assets/161371893/df38b7f3-7f08-466a-9bab-9abeda81b660">

**Comment by unitof** [comment]
Are these actually 4 things they're comparing? I thought from left to right it's worst to best.

**Comment by MiguelJeme** [comment]
I read these as the category breakdown of the framework the intro mentions

**Comment by unitof** [comment]
Well I can definitely & very easily break them into a 2x2 grid, including
with some hover effects.

But just want to make sure—they really seem like tiers to me, from lowest
to highest.

“Feral capital” just sounds to me like something they’re saying is bad.

I can forward to Kyasha to ask.

Comma,
Jacob Ford
Designer <https://jacobford.com> About <https://nocomment.llc> Town
<https://geistlist.email>

**Comment by unitof** [comment]
Dunno if this is anything, but made some pulsing arrows:
https://srfcapital.vercel.app/measure

Lemme know thoughts.

I can go with Miguel’s 2x2 grid approach instead, and have them hover
around a bit in their quadrants. Anything I can label the axes?

Comma,
Jacob Ford
Designer <https://jacobford.com> About <https://nocomment.llc> Town
<https://geistlist.email>

**Comment by MiguelJeme** [comment]
Reviewed this with Kyasha and we think move forward with the cycle through slides option to add motion/dynamism

**Comment by MiguelJeme** [comment]
<img width="861" alt="Screenshot 2024-03-06 at 2 20 48 PM" src="https://github.com/yescomment/jm-srf/assets/161371893/c9c6ee48-ecff-4db9-a3f5-b81bf1cc9e9a">

Moving forward with this layout.

- Adding a marker that travels up the line chart with every slide
- [Inspo motion](https://www.pinterest.com/pin/346284658865455648/)

**Comment by unitof** [comment]
@MiguelJeme Would love a lookover again now: https://srfcapital.vercel.app/whealth+

**Comment by MiguelJeme** [comment]
<img width="797" alt="Screenshot 2024-05-06 at 6 54 44 PM" src="https://github.com/yescomment/jm-srf/assets/161371893/8b8b40cf-14ae-42e4-9249-8bb9b39a1245">

Its looking good, love how the title/capital lines continue shifting. 

Ideally getting it as close to the mock design as possible: 
1. Adding the 4 item "menu" to track the relationship between the 4 slides 
2. "Capital" two weights lighter and more left aligned 
3. Green underline to visually anchor the text
4. Should the graph line start to grow at feral capital, it seems delayed starting after ?

**Comment by unitof** [comment]
Making nav separate issue #17
