### ISSUE TITLE
SRF Impact: Strategy page

### ISSUE THREAD

**Issue by MiguelJeme** [yescomment/jm-srf#6]
Treat this page like FAQs with collapsing sections to minimize scrolling

<img width="1095" alt="Screenshot 2024-03-06 at 2 30 47 PM" src="https://github.com/yescomment/jm-srf/assets/161371893/52553ea7-5ac1-4d28-9ad9-e1a4397c1906">

**Comment by unitof** [comment]
Do we still want this with new copy? https://srfimpact.vercel.app/strategy

**Comment by MiguelJeme** [comment]
This strategy page seems ok as is. I think the https://srfimpact.vercel.app/areas-of-focus  could more so benefit from this treatment, starting from "collective ambition".
