### ISSUE TITLE
Impact Video

### ISSUE THREAD

**Issue by unitof** [yescomment/jm-srf#7]
- [ ] Do we want video & hero BG to pure white (as-is) or theme light color `#edede9`?
- [ ] @MiguelJeme let me know when Impact video is ready! I can drop it right in srfimpact

**Comment by MiguelJeme** [comment]
Will share as soon as i can. My thinking was that white would probably color match the best from video export.

**Comment by MiguelJeme** [comment]
I uploaded 2 videos, one for each site, [Here](https://drive.google.com/drive/folders/1bGv3a7sBl0Avp1IZ8oAvsv-4lXiX32U4)
